services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $openweathermapApiKey: '%openweathermap.api_key%'
            $kernelRootDir: '%kernel.root_dir%'
            $webDirectory: '%web_dir%'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Admin,Entity,Model,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\UserProvider\FOSUBUserProvider:
        arguments: ['@fos_user.user_manager', {facebook: facebookId, strava: stravaId, twitter: twitterId}]
